### ISSUE TITLE
Ultimate 64 Elite - issue with Epyx Fastloader

### ISSUE THREAD

**Issue by Marc91360** [GideonZ/1541ultimate#127]
Ultimate 64 Elite V1.26 - 3.6a
2 real SIDS (8580 in socket 1 and 6581 in socket 2)

When selecting the "Epyx Fastloader" as a booting cartridge, the C64 doesn't boot anymore. (it works great with other cartridges).

I have a black screen; I can hear the drive reset, and some kind of video signal is probably send to the monitor, for the "no signal" message disappears- but no C64 booting screen.
 
I can still access to the Ultimate menu by pressing the power button. From there, using F5, I can reset or even reboot the C64, and it works gret from there.
 
But as long as I have "cartridge Epyx Fastloader" as a booting cartridge, I can not  start the Ultimate 64 from the power button.

![Epyx](https://user-images.githubusercontent.com/60089223/72707580-0af64680-3b61-11ea-9a0a-3b0dff2d8368.jpg)

**Comment by GideonZ** [comment]
Confirmed.. Will investigate.

**Comment by uffejakobsen** [comment]
@GideonZ Do you have special handling for the Epyx Fastload cartridge in the FPGA ?

Epyx Fastload cartridge uses the de-charging of a capacitoy to unmap itself from memory after reset

See schematics and pcb photo:

https://rr.pokefinder.org/wiki/File:Epyx_FastLoad_Schematics_large.png

https://rr.pokefinder.org/wiki/File:Epyx_FastLoad_top_opened.jpg

**Comment by GideonZ** [comment]
Hi Uffe,

Yes, the U2+ has special handling for the Epyx Fastload cartridge, based on the decharging of the capacitor. In fact, the handling works on the U2+ but seems to fail now on the U64, most likely due to the things that happen after reset, like SID detection. The U64 keeps the RDY of the processor low after deasserting reset, to be able to access the memory bus. During this time, most likely the capacitor 'discharges' and the cart doesn't boot correctly. I will have to inihibit discharge of the capacitor during RDY low, and it will likely be fixed.

Gideon

**Comment by uffejakobsen** [comment]
Hi Gideon,

Thanks for the explanation - that sounds like a good theory :-)

**Comment by GideonZ** [comment]
Fixed. Will appear in 1.28 and higher (3.7)
