### ISSUE TITLE
Kerberos midi interface incompatability

### ISSUE THREAD

**Issue by matozoid** [GideonZ/1541ultimate#139]
Spotted this on the Kerberos-midi mailing list: https://groups.google.com/forum/#!topic/kerberos-midi/DfAH_oXW2Ow

Maybe someone can give the cartridge a try, or debunk some of the claims there.

**Comment by t-h-e-joker** [comment]
Facts with the Kerberos cart in the Expansion port of the U64:

V1.24 or older:
--> works

V1.26 / V1.28: with default settings (cartridge preference = auto) 
--> starts always with the C64 Basic prompt.  After a manual reset, the Basic prompt appears again.

V1.26 / V1.28: with default settings (cartridge preference = external) 
--> starts always with the C64 Basic prompt.  After a manual reset, Kerberos works.

The problem is known and also occurs with some other external cartridges since V1.26.

**Comment by Frank-Buss** [comment]
Kerberos should work, if these IO addresses are not used by the other cartridge:

$de00-$de0f after MIDI is enabled, not used after reset, only 2 or 4 registers in the range are used, see https://codebase64.org/doku.php?id=base:c64_midi_interfaces
$de39-$de3f configuration registers, always enabled
$df00-$dfff one SRAM bank of the 128 kb RAM extension, always enabled

It also pulls EXROM low after reset, for the menu autostart, which is then mapped to $8000-$9fff as ROM from the flash chip. For the full functionality, including flash write after the menu started, it needs all kinds of combinations for GAME and EXROM, including the Ultimax mode (GAME low, EXROM high) and the 16 k cartridge mode for a custom BASIC (GAME and EXROM low).

**Comment by GideonZ** [comment]
Kerberos works just with the latest firmware (1.32).  This was verified by @iamtsb (Martijn Wieland)

**Comment by matozoid** [comment]
Cool!
