### ISSUE TITLE
128 mode, REU transfer from function rom corrupted data

### ISSUE THREAD

**Issue by bvl1999** [GideonZ/1541ultimate#142]
For use in a 128 function rom, I use some block copy routine. One of the uses for this is to copy a bit of code/data from the function rom to ram. 

The block copy routine can use the REU for this if one is available, and, as long as the source for the copy is internal rom or ram, that works great (also for a function rom in socket U36). This also works as expected with a Commodore 1750 REU, also for copying from a rom in its external function rom socket. 

However, if the source for the copy is a virtual external function rom as provided by the the UII (c64 and cartridge settings, cartridge set to custom external 128 rom), the data that gets copied to the REU gets corrupted. 
I attached a test rom image which is based on the following code:

Example code: 
    lda $ff00
    and #%00001111
    sta $ff00
    lda #$80
    sta $df03
    lda #$00
    sta $df02                   ; $8000 in system memory, this is the start of this rom
    sta $df06
    sta $df05
    sta $df04                   ; bank 0 address 0000 in REU memory
    sta $df09                   ; no IRQ on completion
    sta $df0a                   ; do not fix system or reu address
    sta $df07
    lda #$20
    sta $df08                   ; copy $2000 bytes
    lda #%10110000              ; copy from current memory map to reu, autoload address enabled, don't wait for $ff00
    sta $df01
    lda #$20
    sta $df03                   ; $2000 in system memory, this is ram in bank 0 (as this is the default target bank for dma operations)
    lda #%10110001
    sta $df01                   ; copy from reu to current memory map

[u2reutest128.zip](https://github.com/GideonZ/1541ultimate/files/4673727/u2reutest128.zip)

Unzip, transfer to your UII+, and use it as custom external 128 function rom.
After it finished running (it should clearly indicate it is running, and if it found any issues), you can use the C128 ML monitor to inspect ram in bank 0, $2000-$4000 and compare it to rom in bank $0a $8000-$a000. It should be identical if things worked. On my hardware the result is not identical, and seems to somewhat change depending on timing settings in the C64 and cartridge menu (but not entirely sure if that is just random changes or really a result of changing those settings)

**Comment by GideonZ** [comment]
I wonder if this behavior also occurs on a C64 when copying larger areas from a cartridge ROM to REU. Because in essence there is no difference between a C128 function ROM and a generic cartridge ROM, when the copying itself is concerned.

Basically there are two separate units that run in parallel; the "slot master" and the "slot slave". The REU is forwarding its DMA request to the slot master, which places the address on the bus. In this case you are reading, so it will pick up the data from the bus at the end of the cycle. Then, it will issue a write to the REU memory. The slot slave "sees" the address and decodes it as if the CPU was reading it; issues a read from its local DRAM and presents the data onto the bus before the end of the cycle. The slot master is supposed to pick up this data.

What could possibly go wrong?
- The address is placed too late onto the address bus of the machine, which causes it to initiate a RAM access, which may corrupt the data near the end of the cycle?
- The address sampled by the slot slave is corrupt, because it is not yet present on the address lines (read before write), or, due to capacitive loading of the address bus, it is not yet stable
- The data is presented too late on the data bus by the slot master. The slot slave reads the data bus before the master has managed to put the byte on the bus.
- The performance of the memory controller is not sufficient to keep up, as it is also shared with the 1541 CPUs and the application CPU. However, both slot master as well as the slot slave are on the high-priority input of the memory arbiter, so I'd expect this to run correctly.

Because the U2+ is asynchronous in respect to the CPU bus, the moment at which the address and data is output and sampled jitters somewhat with respect to the PHI2 clock.  However, one would expect that the master and slave jitter around the PHI2 edge in the same way, as they are synchronous with each other. So, if it goes wrong only *sometimes*, I would expect some influence from the machine; maybe just by something as simple as the actual value that was present on the bus before the cycle starts. 

In order to debug this, it would maybe be good to
- Test this on a C64 with a standard ROM
- Let the REU perform a verify, preferably with fixed addresses so that it will retry the same address over and over again and stops upon failure. This will allow me to trigger on the fail and see the bus-activity during this failing cycle.

**Comment by bvl1999** [comment]
What I can say is that it also goes wrong with a 256 byte transfer (that is what I noticed originally), and that the result isn't the same between tries, but it going wrong is rather consistent.
Creating a test case that does a verify seems simple, will take a look at that. As to testing in 64 mode, can do that but I can only test that in 64 mode of a 128DCR, or on an Ultimate 64 Elite, not on a 'regular' 64. Except for the little bit dealing with $ff00 which is simply not needed on a c64, the c64 code should be identical.

**Comment by GideonZ** [comment]
I know how silly it sounds to do a verify of one single byte with a transfer length > 1... I think it is one of the least used operation modes of the REU... The transfer length is then simply the number of tries.. ;-) The good side of it: you only need to know one byte of the ROM and place this in REU memory somewhere.

**Comment by bvl1999** [comment]
hmm.. ok. thinking a bit more about what you are suggesting..
it would be good to have known data in the reu, and veriffy that against that same data in a cartridge rom.. using a single byte from the rom, and copying that into system ram, and from there into the reu should get that data there reliably. After that, do repeated one byte verifies against the byte in rom?

**Comment by GideonZ** [comment]
1) You can simply load a known good copy of the ROM into system memory, then use the REU to copy it into the REU memory; then verify the entire ROM against the REU memory.
2) You can load the known copy of the ROM into the REU, using the Ultimate Menu (name it .reu), and verify the entire ROM against the REU memory, using the REU.
3) You can copy one known byte from the ROM data to the REU, using transfer length 1. Then, verify the ROM to that one single byte by setting the REU control register to *not* increment either address. Then you can set the transfer length to $FFFF to verify that single byte thousands of times.

**Comment by bvl1999** [comment]
Ok, clear.
Was also thinking to make a simple look to try different transfer lengths to see if that matters at all (ie, does the time that dma is being held play any role)

**Comment by bvl1999** [comment]
[u2reutest1.zip](https://github.com/GideonZ/1541ultimate/files/4674640/u2reutest1.zip)
64 and 128 cartridge rom images, and sources for both (they are identical except for a bit of startup code), they execute the first test you proposed.
As you expected, this also happens with 64 cartridges.

**Comment by bvl1999** [comment]
Also, while I haven't been able to test on a real C64, this issue also occurs on my U64e.

**Comment by GideonZ** [comment]
Excellent; then it must be a logical / timing problem in the FPGA, and not an issue caused electrical limitations. I think I can therefore safely assume that it will also occur on a real C64. Well done, Bart!

**Comment by bvl1999** [comment]
[u2reutest3.zip](https://github.com/GideonZ/1541ultimate/files/4677221/u2reutest3.zip)
The 3rd test you proposed, again 64 and 128 cart images, and the sources for those. It fails with the same consistency (every transfer fails).

**Comment by GideonZ** [comment]
This problem was caused by falsely declaring the C64 as 'stopped', which turns off the cartridge access after some grace cycles. Broken by optimization. :-)
