### ISSUE TITLE
U64 Modem, cannot use external cartridges

### ISSUE THREAD

**Issue by grue74** [GideonZ/1541ultimate#197]
Enter the Modem settings menu
I have set up a modem in the $dfxx area.
I have an external IDE64 cart connected.
Cartridge preferences: External
Bus Operation Mode: Dynamic
Modem connection is impossible.

to fix 
Set Cartridge preference to Internal
Modem starts to work.

But I cannot use the swift link with my ide64 at the same time. Is this a bug or by design?

**Comment by GideonZ** [comment]
Hi Grue... this is by design... of the Commodore 64. You can have only one cartridge attached at any time.

_How about bus sharing / expanders?_ 

Bus sharing through an expander only works when memory regions do not overlap / conflict. When configured for DFxx, the ACIA occupies DF00 - DF03; only four bytes of this range. I am not enough familiar with the IDE64 to know exactly whether the DF00-DF03 range is used. If it is not used for IDE64, you can enable bus sharing. Set the cartridge preference to Manual. When it is set to manual, four additional items are enabled right below. You could set everything to external, except for I/O2 (DFxx) and Interrupts; which you need to set to 'Both'. This configures the bus bridge such that IO2 accesses end up on the external cartridge port as well as on the internal cartridge port, and that the NMI/IRQ interrupt from the ACIA is combined with the NMI/IRQ from the cartridge port. This should enable both ACIA as well as IDE64.

**Comment by grue74** [comment]
Thanks for the friendly explanation for the extended take on bus settings sharing.

I had overlooked those as "Dynamic" seemed to work ok on all other cases like IDE64 + Internal REU. Somehow this ACIA emulation adds an exception there. Then again I SHOULD have seen this Cartridge Preference option and try to fiddle with it. But since internal REU already worded, I somehow overlooked that..

But now everything works: External IDE64 cart, Internal REU, and Internal ACIA at $df80. I had to set:

Roms = Both
IO1 = External
IO2 = Internal
Int = Both

With just IDE64+REU it worked with Automatic settings. Somehow this ACIA emulation cannot share IO1 and IO2 area without manual intervention :)

Thank you again!

I'll make another posting about getting this work on Facebook/youtube later as it needs $df80 patched swiftlink driver, I think most of the users won't be able to do that themselves...
