### ISSUE TITLE
REU and turbo mode

### ISSUE THREAD

**Issue by p-a** [GideonZ/1541ultimate#204]
Seems like anything above 2MHz makes REU transfer times very unpredictable. Is it possible to make it transfer 1 byte per cycle at all speeds?

Ultimate 64 V1.37 - 3.9. PAL. HDMI.

**Comment by markusC64** [comment]
I wouldn't like that as default. With Geos, RAMDISKs are so fast - that's wonderful.

Anyway, did you thought of using the speed control register to switch to 1 MHz bedore REU transfer and back to the desired speed after that?

**Comment by p-a** [comment]
I want the REU to transfer 1 byte/cycle, in sync with the current CPU (turbo) speed :) So yes - faster.
AFAICT, this works reliably for 1 and 2MHz, but going over that and it isn't predictable.

**Comment by GideonZ** [comment]
The current available memory bandwidth does not allow this speed. However,
this may improve (maybe up to 8 MHz or so) when the REU is moved into the
C64 clock domain. It's now part of the U2+ clock domain, which is fully
asynchronous to the C64. The original cartridge bus signals are now the
bottleneck.

**Comment by p-a** [comment]
Ok! 8 MHz would in fact be excellent for my purposes :) Do you have a rough estimate on when this will happen?

**Comment by p-a** [comment]
@GideonZ As far as I can tell, this limitation seems to apply for accessing ROM too? I created a EF cart with some code aimed for 48MHz mode, but it doesn't run nearly as fast as when I put the exact same code in RAM.

**Comment by GideonZ** [comment]
Of course.

**Comment by p-a** [comment]
Okay, good to know!

**Comment by GideonZ** [comment]
But... If the demand is there, I could look into accelerating it. What
basically happens now is that cartridge bytes are served by the ultimate
application in relation to the PHI2 clock. The ultimate 2+ part of the U64
doesn't know if it is connected to U64 internals or whether it is connected
to a real C64 cartridge port. This is so, because the U2+ part is basically
a U2+ in _all_ regards, including the interface of the cartridge bus. The
only modification made is the DMA channel, which the REU also makes use of.
(DMA channel is access from the U2+ into the U64 subsystem...) This channel
is still highly inefficient, but already faster than 1MHz. A lot can be won
by moving the cartridge emulation logic into the U64 domain. Obviously, not
the entire cart ROM can reside in FPGA RAM. Imagine EasyFlash for instance;
it is just too big. However, a local cache in the 48MHz domain could help
to speed things up, but you will never be able to truly rely on cycle
counting as you may encounter cache misses. Of course, if you know what you
are doing, you can make fast deterministic loops that remain in the cache.

As you understand... and what has already proven to be so... Changing
things away from how it had always been does introduce new
incompatibilities elsewhere.
