### ISSUE TITLE
Inconsistent Insert Blank/Remove Disk behavior in Menu-F5-Drive A/B

### ISSUE THREAD

**Issue by HowlinAlan** [GideonZ/1541ultimate#237]
The Insert Blank/Remove Disk options still exist for 1541 drives, but there are no similar options for D71s or D81s. 
Also, the "Save as Binary/Save as GCR" options available for 1541s are confusing. Is this meant to be "Save as D64/Save as G64"? That would be much clearer for the user.
Additionally, the "Save as Binary" option creates a D64 that seems to work fine, but is 172K in size, rather than the usual 171K.

Is the Insert Blank/Remove Disk feature even necessary? All it does is create a bunch of additional confusing entries in the menus, and it's easier, quicker, and more sensical to use the F5-Create options to create a disk image anyway. I suggest these options be removed.

**Comment by markusC64** [comment]
"Save as Binary" means: Save as D64, Save as D71, Save as D81 - depending on drive type and if disk inserted is single or double sided.
"Save as GCR" means: Save as G64, Save as G71 - depending on number of sides. It is not usable for a 1581 because that drive does not use GCR encoding.

"Remove disk" works (resp. should work) for all drive types and all supported images.

"Insert blank" inserts a blank disk into a 1541 or 1571. Depending if one or two sides are written in between, Save as Binary resp. Save as GCR will save a D64 resp. G64 or a D71 resp. G71.

And yes: Blank disks are usefull, e. g. if you do not intend to save the disk later... or you need a nonstandard format - some speeders allow formatting to 40 tracks. Or for generating MFM disks in the 1571 with some tool that will format them (like big blue reader).

And otherwise I think those options should be kept.

**Comment by markusC64** [comment]
Oh, I should add: In the 1571, MFM disks (that is disks that contain at least one MFM track) have to be saved as GCR - because G64 and G71 has been extended to allow savong of MFM tracks.

**Comment by GideonZ** [comment]
A blank disk is an unformatted disk. This is not the same as creating a D64
and mounting it; as it would be formatted already.

You mention that it is inconsistent; as such an option does not exist for
the 1581. (It *does* exist for the 1571!) The reason behind this is that
the 1581 does not support GCR. Disk images for the 1581 are *not* loaded
into memory, but access to the disk image is done directly on the file.
Even though the emulation may support an unformatted disk, the D81 file
format does not provide a way to encode 'emptiness'. And because there is
no GCR support, there is also no ".G81" file format.

So, yes... the option to insert a blank disk is necessary.

I can see your point about "Save as Binary" / "Save as GCR". I changed it
to a common name, so that I don't need multiple menu entries for the same
thing (with a different name). At the moment of creating the menu it is not
yet known whether the disk to be saved is single or double sided.

When you mentioned "Inconsistent *BEHAVIOUR*", I thought for a moment that
you meant that it acts differently at different times, randomly. This is
not what you meant, as it seems.

**Comment by HowlinAlan** [comment]
Thanks for the explanations, Markus and Gideon. That all makes perfect sense.
You're right, Gideon, "behavior" wasn't the most precise word I could have used.
