### ISSUE TITLE
U64: Krestology demo huge graphics problem

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#287]
Hi

Krestology by Crest: https://csdb.dk/release/?id=11586 has huge problems with the display on the U64.

![image](https://user-images.githubusercontent.com/7808413/190699416-40f11e10-35d7-4d52-9115-df035def5e63.png)
![image](https://user-images.githubusercontent.com/7808413/190699452-7029f101-b977-4fdc-a740-a5c16cd5969e.png)

U64 1.41 - 3.10c

**Comment by marty41** [comment]
I just wanted to comment that you linked to Krestology instead of Krestage, but you already edited the text.. ;)

Krestology seems to work fine for me. Same FW used. U64 Elite 1.41 3.10c

![grafik](https://user-images.githubusercontent.com/23246486/190707864-93b24e73-0adb-407c-b852-59d6c34e6a5e.png)

I made a short video from the first part playing:

https://youtu.be/-qt26bLPnKg

**Comment by TomCat666** [comment]
Oh well, I forgot I had the Turbo Control set to "TurboEnable Bit" because one of the demos supported it. If I turn it completely OFF then Krestology works perfectly. Sorry for this. Demos should be tested with Turbo completely off, not even d030 should be enabled.

**Comment by Grrrolf** [comment]
In the past Gideon mentioned that when filing these type of bug reports, it would help a lot (and save a lot of time) when you isolate the code in such a way that when he runs the programme it starts where the issue starts.

Are you using custom roms or vanilla roms? Any other customizations or cartridges / peripherals attached to / enabled on the U64?

**Comment by TomCat666** [comment]
I accidentally left on "TurboEnable Bit" in the U64 settings, aparently Krestology trash-writes to $d030 and enables turbo :) Sorry for the false report.
