### ISSUE TITLE
Misc feature requests for the U2+

### ISSUE THREAD

**Issue by Zibri** [GideonZ/1541ultimate#310]
1) connect one or two playstation 2 gamepads to the u2+ and use them in c64 games.
2) mirror the c64 SID on the emulated ones (as you do now) and record the sound on a wav file (missing).
3) full iec (sniffing) and tape log to file
4) add missing STOP and reset TAPE in dropdown menu
5) capture tape to TAP starts right away, while it should wait for the motor to start and stop (like in vice)
6) tape and drive wobbling and alignment are not emulated.
7) a machine code monitor would be very useful to have without using any cartridge, like in vice. it could be started by pressing the freeze button and offer a similar functionality (vice is opensource) of the vice monitor.
8) the freeze button could also be customizable, for example to run a program or disable drive A or other functions without needing to go to the menu.

Another great function would be to be abe to connect a usb cable between the u2+ and a pc and have a virtual XOOM cable to talk directly to IEC bus.

**Comment by Grrrolf** [comment]
You may want to split each feature request into one GH issue.

**Comment by GideonZ** [comment]
There should be one ticket per feature request.

#1 Not possible, as already mentioned in another thread.
#2 At the expense of what other feature? The FPGA is already full and this requires extra logic cells. I'd say: Use the U64 for this, as it supports real time audio streaming over the network!
#3 I can see that this is useful, but as #2; requires extra logic cells. Tape logging is already there; it is called Save to TAP, but yes, this does not log the change of the motor on/off control signal.
#4 Stop tape is certainly there!  Reset tape is not required; you can simply start the TAP file again.
#5. I have to check this, but I am pretty sure that it waits for the motor to run. I.e. it only counts the time when the motor is running. I even think it handles the motor speed up and slow down as well. 
#6 Fortunately not. :-)  Not gonna happen!
#7 Yes.. It would be useful. Agreed!  I had actually foreseen that someone would write a monitor on top of the API coming in V3.11. I think this is a more convenient solution than having a monitor on the C64 itself. But maybe both are useful for their own purposes.
#8 The freeze button is not configurable, because it is a hardware button. It activates the freeze logic in the cartridge emulation. The software doesn't even see it.

**Please note that references to Vice are ignored, now and in the future. It is irrelevant what vice can do or cannot do. This is a different code base. Vice is a software emulator, while the ultimate is not.**
