### ISSUE TITLE
[U2+L] espc3_v1.1.est error - ESP32 Program failed.

### ISSUE THREAD

**Issue by blindguy** [GideonZ/1541ultimate#426]
Loaded up 3.11a and tried to flash espc3_v1.1.est and got an error but not alot of details. It just says ESP32 Program failed.

Tried resetting back to 3.11 and then back to 3.11a but still same error.

Any thoughts on logs or what I can try to do to get the wifi going?

I have a Ultimate-II+L Cartridge - do I need the Tape adapter plugged in to do the flash?

**Comment by GideonZ** [comment]
**This comment does NOT apply to WiFi modules shipped after mid-June 2024.**

Unfortunately, a number of WiFi modules have been sent out with an incorrect resistance value mounted on the small WiFi PCB. The worst thing about this is that I have no way of telling who received these modules and who did not. The problem is indeed that the firmware cannot be loaded when the wrong resistor value is mounted. The long story: When designing the WiFi board, I overlooked a resistor on the cartridge itself, used the same resistor value on the WiFi module to pull the signal in the opposite direction, resulting in a signal that is neither '0', nor '1' but somewhere in between. I discovered this before shipping the WiFi modules out and decided to patch them by putting another resistor value on the WiFi module. These resistors come in strips. Unfortunately one of these strips had 12.7K ohm in them, instead of the intended 2.7K.

There are three options:
1) I am sending you a new module. Disadvantage: takes at least 10 days before you can enjoy WiFi.
2) You can tap or cut a small resistor from the Ultimate-II+ cartridge PCB with small pliers or a blunt screwdriver (no effect on the warranty). This is a very small and easy procedure (see below) that solves the problem immediately.
3) If you have the means to do so, you can also mount the correct resistor value (2.7k or 3k, size: 0402) on the WiFi module on location R6.

Note that when you remove the resistor from the cartridge board, the cartridge will still function normally even without the WiFi module.

Can you let me know what your preference is?

Yours sincerely,
Gideon

Ad 2):
Locate Resistor to remove. Above 'a' from Ultimate, right of the white 'C'.

![image](https://github.com/GideonZ/1541ultimate/assets/11030985/dffb6b45-ebde-45b5-92a0-e2541c1d6a56)

2) Use a side cutter to shatter the resistor:

![image](https://github.com/GideonZ/1541ultimate/assets/11030985/d83476bf-7e94-46a1-bcaa-65e1781459ae)

If you don't have a side cutter like this, you can also use a screwdriver or any other blunt object to apply a lateral force on the resistor from left to right. Since they are only 1 x 0.5 mm in size, they don't need much to get broken off. Don't dig into the board itself, so do not use a sharp object with too much downward force.

3) Check if the resistor is gone and remove remaining loose particles:

![image](https://github.com/GideonZ/1541ultimate/assets/11030985/a020480d-1d80-463f-9f06-b91bf7ed62f6)

**Comment by blindguy** [comment]
Thanks for the prompt response.  

If I pull the resistor off will I need to solder in the new resistor to get wifi working?  I don't think my skill set is up to installing small surface mount resistors like that.  I normally send my electronic work out to a guy in Denver but he is over in France for summer vacation.  Let me reach out to a few folks and point them to this page and see if I can get someone here in the US to do this.  If you happen to know anyone in the US that you trust please let me know and I'll reach out tot hem and see if they can assist.

**Comment by GideonZ** [comment]
There is no need to replace the resistor. Option #2: just carefully chip off one resistor from the cartridge itself.

**Comment by blindguy** [comment]
Before:
![20240709_133443](https://github.com/GideonZ/1541ultimate/assets/11575103/3f356de3-2e3a-4a15-a1a2-0a3830747856)

After:
![20240709_133659](https://github.com/GideonZ/1541ultimate/assets/11575103/6495c766-19d8-44bd-8e45-ff7d2b2a063f)

Still getting same error:
![20240709_091923](https://github.com/GideonZ/1541ultimate/assets/11575103/f151b05e-13b2-4e6d-9ff6-da5efab6665f)

**Comment by GideonZ** [comment]
Interesting. I'll just send you another module.

**Comment by GideonZ** [comment]
Send me an e-mail with the order number so I'll re-ship it.
