### ISSUE TITLE
[U2/U2+/U64 v1.18/3.4c] File browser does not show the unit bytes

### ISSUE THREAD

**Issue by Grrrolf** [GideonZ/1541ultimate#74]
While the Ultimate file browser adds the unit K after kilobytes, it does not add a B when the unit is bytes. This concerns when browsing both the USB storage file system and inside the disk images.

An example from the file system:
![image](https://user-images.githubusercontent.com/10052794/56620033-cff1d180-6627-11e9-9c8a-5be1ef5cd081.png)

And an example from inside a disk image:
![image](https://user-images.githubusercontent.com/10052794/56620174-4f7fa080-6628-11e9-8747-1746e94d835c.png)
ps: I used the remote menu for the ease of creating screenshots. It looks exact the same in the freeze interface type.

**Comment by GideonZ** [comment]
K is not a unit...

**Comment by Jumpman64** [comment]
...it means 1000 :)

Would it be possible for you to include an option to choose between "bytes" and "blocks"?

**Comment by Grrrolf** [comment]
If that's how you guys roll, then, I can do that to. Actually, _K_ is a unit of temperature (Kelvin). 

But the above is of course not the issue. The alignment of the values are. The current alignment suggests something is missing. Solutions to make it look less confusing is to either align the value to the right or add a b for byte. There might be other solutions. Whatever is the easiest and least confusing.

**Comment by Jumpman64** [comment]
Sorry for kidding. The alignment could look a bit messy imo too if there's a B/K size mix like on your screenshot.
Let's see:
The "size" column has a fixed length of 5 chars - max. 4 numbers and 1 letter/space.
There is 1 space to the left to separate the file type and even 1 space to the right (pos 40). 
Size flow is 999_ -> 1K -> 999K -> 1M -> 9999M
It's not a KB unit because it shows 1K @1000 (bytes).

So a simple B would do the cosmetic trick but B means bytes and then someone could think K is KB, what it isn't. Or moving <=999 one step to the right, someone could say that doesn't look good either ...but maybe i rather would vote for that. (if it doesn't bloat the code)
That's kind of a "No matter what you do, you do it wrong." situation.  :)

**Comment by Grrrolf** [comment]
Lots of confusing stuff with all the k, K, b and B's. 
Closing this ticket since it's just a small nuisance.
