### ISSUE TITLE
SID Player: wrong SID selected on SidFX

### ISSUE THREAD

**Issue by dabadab** [GideonZ/1541ultimate#86]
In configurations where SID#1 is a 8580 and SID#2 is 6581, the 6581 is selected for all tunes that specify a SID model.

The bug is caused by getRequiredSidInfo in detectionwrapper.asm: for 8580 it returns $02 instead of $00.

**Comment by WilfredC64** [comment]
Thanks for creating an issue for this. The current implementation is that it always defaults to 6581 when the SID tune header specifies that the SID model is unknown or when the tune is made for both 6581/8580. However, the comment I made in the code mentions that it should select socket 1 when this is the case and this is preferred because most people put their preferred SID model in socket 1 I think.

About the suggested fix, I think it can be solved in a more simple way so I will create another pull request for this.

**Comment by WilfredC64** [comment]
When the SID model is unknown it always switches to socket 2 which is not preferred. I will fix this in another pull request.

**Comment by dabadab** [comment]
There are actually two issues in play:

1. getRequiredSidInfo returns models using the .sid header numbering (1: 6581, 2: 8580) and this is passed to setSidFxModel which expects the models in SidFX numbering (0: 8580, 1: 6581). This is clearly a bug.

2. The discrepancy between the comment and the actual behavior in cases of an ambiguous chip model. I think in this case the solution in the comment (always using Sid#1) makes more sense but there is certainly no only true way.

**Comment by WilfredC64** [comment]
Thanks for making it more clear. It is indeed a bug. I hope you don't mind that I will fix it a bit differently.
